apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener

metadata:
  name: python-app-listener
  namespace: nguyentaihieu004-dev

spec:

  serviceAccountName: pipeline

  triggers:

    - bindings:

        - ref: python-app-binding

      template:

        ref: python-app-template